Vagrant::Config.run do |config|
  config.vm.customize do |vm|
    vm.memory_size = 2048
  end

  config.vm.box = "macosx-snowleopard"
  config.vm.forward_port("ssh", 22, 2225)
  
  Vagrant::Config.run do |config|
    config.vm.provision :shell, :path => "setup.sh"
  end 

  config.ssh.private_key_path = "~/.ssh/id_overtone"
end
