Vagrant::Config.run do |config|
  config.vm.customize do |vm|
    vm.memory_size = 1024
  end

  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
  config.vm.forward_port "ssh", 22, 2226

  config.vm.forward_port "buildbot pb",  9989, 9989
  config.vm.forward_port "buildbot web", 8010, 8010

  config.vm.boot_mode = :gui
  config.ssh.max_tries = 100

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "vagrant_main"
    chef.log_level = :debug
  end

end
